### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by shuluoshu** [thodan/bop_renderer#4]
Hi @thodan  @MartinSmeyer 
I'm building the off-screen on server:  
In CMakeList.txt, the python version is python2.7,  I wonder if I can use python3.6? and if Ok , should I update pybind11 in 3rd folder? 

Thanks.

**Comment by thodan** [comment]
Hi shuluoshu, did it work with python 3.6?

**Comment by shuluoshu** [comment]
I successfully build it with python2.7 on the off-sreen server. python3.6 untested.
