### ISSUE TITLE
"make" failed, undefined reference to `YAML...

### ISSUE THREAD

**Issue by Liuchongpei** [thodan/bop_renderer#6]
@thodan Hi,
**When I execute the last "make" command, the following error appears:**
CMakeFiles/renderer.dir/src/UtilIO.cpp.o: In function `YAML::Node::Scalar[abi:cxx11]() const [clone .isra.64]':
UtilIO.cpp:(.text+0x221): undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]'
CMakeFiles/renderer.dir/src/UtilIO.cpp.o: In function `readPosesYaml(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<Pose, std::allocator<Pose> >&)':
UtilIO.cpp:(.text+0xe85): undefined reference to `YAML::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
UtilIO.cpp:(.text+0x10af): undefined reference to `YAML::detail::node_data::size() const'
UtilIO.cpp:(.text+0x1ff0): undefined reference to `YAML::detail::node_data::mark_defined()'
UtilIO.cpp:(.text+0x2264): undefined reference to `YAML::detail::memory_holder::merge(YAML::detail::memory_holder&)'
UtilIO.cpp:(.text+0x22b1): undefined reference to `YAML::detail::memory::create_node()'

...There are some similar tips about YAML, I omitted them...

CMakeFiles/renderer.dir/src/UtilIO.cpp.o:(.rodata._ZTIN4YAML18TypedBadConversionIfEE[_ZTIN4YAML18TypedBadConversionIfEE]+0x10): undefined reference to `typeinfo for YAML::BadConversion'
collect2: error: ld returned 1 exit status
CMakeFiles/renderer.dir/build.make:408: recipe for target 'renderer' failed
make[2]: *** [renderer] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/renderer.dir/all' failed
make[1]: *** [CMakeFiles/renderer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**I have downloaded the source code of yaml-cpp version 0.5.2 and installed it as follows:**
cd yaml-cpp
mkdir build && cd build
cmake .. && make
make test   #Test passed,
sudo make install

I have been bothered for several days, and I will be very grateful if you can help.

**Comment by Liuchongpei** [comment]
The problem is solved

**Comment by tanmay8266** [comment]
Hey could you please elaborate how did you solve the problem, I am facing the same issue
